apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/michelm117/cycling-coach-lab'
    path: deployments/cycling-coach-lab
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valuesObject:
        image:
          tag: {{ .Values.image.tag }}
        postgresql:
          persistence:
            enabled: {{ .Values.postgresql.persistence.enabled }}
        ingress:
          enabled: true
          className: ""
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: {{ .Values.subDomain }}.newtri-science.michel.lu
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: ccl-review-{{ .Values.name }}-tls
              hosts:
                - {{ .Values.subDomain }}.newtri-science.michel.lu
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: newtri-science
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
