apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/michelm117/cycling-coach-lab'
      path: cycling-coach-lab
      targetRevision: HEAD
      helm:
        valuesObject:
          image:
            tag: '1.3.0'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: newtri-science
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
