apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/michelm117/cycling-coach-lab'
      path: deployments/cycling-coach-lab
      targetRevision: HEAD
      valuesObject:
        ingress:
          enabled: true
          className: ""
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: ccl.newtri-science.michel.lu
              paths:
                - path: /
                  pathType: Prefix
          tls:
           - secretName: cycling-coach-lab-tls
             hosts:
               - ccl.newtri-science.michel.lu
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: newtri-science
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
